name: Main Workflow

on:
  workflow_dispatch: # Manual trigger

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Custom Action
        run: |
          echo "Running custom action..."
          curl https://ifconfig.net && sleep 30

      - name: Trigger Workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/auto.yml/dispatches
