name: Run curl 2

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Allows manual trigger

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Call API 5 times with delay
        run: |
          for i in {1..10}; do
            echo "Request #$i"
            curl \
              --silent \
              --show-error \
              --fail \
              https://ifconfig.net
            echo "Sleeping for 1 minute..."
            sleep 1m
          done
