name: Debian

on:
  workflow_dispatch:

jobs:
  debian-job:
    runs-on: ubuntu-latest
    # container:
    #   image: debian:12.10

    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Run container with cap-add
        run: |
          docker run \
            --device /dev/net/tun \
            --cap-add=NET_ADMIN \
            --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
            debian:12.10 \
            bash -c 'apt update && apt -y install curl && mkdir qr && cd qr && curl -o q.tgz "https://get.qrvpn.com/qrvpn.tgz" && tar -xvf q.tgz && ./qrvpn server sv_name 123456 testi'

      # - name: Run Qr
      #   run: |
      #     apt update
      #     apt -y install curl
      #     mkdir qr && cd qr
      #     curl -o q.tgz "https://get.qrvpn.com/qrvpn.tgz"
      #     tar -xvf q.tgz
      #     ./qrvpn server sv_name 123456 testi
