name: Delete runs

on:
  workflow_dispatch:

jobs:
  main-delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete workflow runs
        # uses: Mattraks/delete-workflow-runs@v2
        uses: daviddusty/delete_workflow_runs/@v2
        with:
          token: ${{ secrets.LOOP }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 2
